### PR TITLE
Frontend Overhaul

### LINKED ISSUE #24: Add Social Preview

### LINKED ISSUE #25: New User Interface (UI)
_Originally posted by @codeIntrovert in https://github.com/diegoborbadev/pytube-downloader/issues/24#issuecomment-1890364767_

### PR DESCRIPTION
**Pull request by codeIntrovert**
# Pull Request: Frontend Overhaul

## Description
This pull request addresses and closes issues #24 and #25 by completely rebuilding every aspect of the frontend. The entire frontend is now built on Python-Flask, providing a more robust and efficient user interface. Extensive testing has been conducted on various devices, including phones, desktops, and displays of varying sizes.

## Changes Made
- Complete overhaul of the frontend architecture
- Python-Flask for improved performance and maintainability
- Thorough testing on phones, desktops, and displays of different sizes
- Closure of issues #24 and #25

## Testing
- Tested on various devices: phones, desktops
- Tested on displays of different sizes, ensuring responsiveness
- Comprehensive testing to identify and resolve any potential issues

## Effort Invested
I have invested significant time and effort into rebuilding the frontend to enhance the overall user experience and address the reported issues.

## Related Issues
- Closes #24
- Closes #25

## Screenshots 
image

## Checklist
- [x] All tests pass successfully
- [x] Code has been reviewed
- [x] Complete overhaul of the frontend architecture
- [x] Tested on displays of different sizes, ensuring responsiveness

### CODE REVIEW

**Comment by diegoborbadev** [comment]
Can you change the color palette to red shades?

**Comment by codeIntrovert** [comment]
Sure I will!

**Comment by codeIntrovert** [comment]
image
## Done

**Comment by diegoborbadev** [comment]
Awesome! I'll review it as soon as possible.

**Comment by diegoborbadev** [comment]
Congratulations on the good work! However, there are some adjustments that should be made:

### Remove the `.old` files
The `.old` files are not needed anymore, they can be viewed in the history of the repository.

### Footer improvements
#### Remove "by" statements
Remove *"created by Diego Borba"* and *"UI Design by Hasan"* statements.

#### Reduce footer size
The footer is too big, it should be reduced.

### Check click-scroll TypeError
When scrolling, the following error is displayed in the console:

image

### Add a loading indicator
Some downloads can be very slow, so a loading indicator is needed.

### Fix header logo link
When you click on the header logo, it redirects to `/index.html`, but it throws a *404* error.

**Comment by codeIntrovert** [comment]
### ✅ Fixed Click Scroll

### ✅ Reduced Footer Size

### ✅ Added loading indicator

### ✅ Removed `.old` files

### ❗ Kept Footer Links for proper attribution of Open Source Creator 
- This is Important to respect contributor's time & effort

### ✅ Fixed header link

**Comment by diegoborbadev** [comment]
> This is Important to respect contributor's time & effort

I agree, but as the number of contributors increases, it will become impractical to list everyone's names on the interface.

**Comment by codeIntrovert** [comment]
Removed Contributer name list

**Review by diegoborbadev — APPROVED** [review]
Approved, just need to fix comments and formatting.

**Pull request merged**
